spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bd-grupo12
    username: root
    password: 4V474r44ng
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
